[build-system]
requires = ['setuptools', 'wheel', 'pandas',
        'scikit-learn',
        'numpy',
        'setuptools',
        'scipy',
        'statsmodels',
        'lavaset',
        'cython',
        'joblib',]
build-backend = "setuptools.build_meta"
